name: DrKonstantinosKatsanos
favicon: null
layout_spectrum: 0.74834
typography_spectrum: 0.52099
title: Dr Konstantinos Katsanos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141408'
    - '#ead578'
    - '#ab9967'
    - '#904d33'
  brandStrength: 0.5
  lightness: 0.17265931516885757
  saturation: 0.5
  rhythmicContrast: 0.46310276817530394
purpose: []
